import { escapeRegex } from '../../../shared/string-utils'
import type { TaskProvider } from '../../../shared/task-providers'
import { escapeLinkedContextControlChars } from './linked-context-control-chars'
import { getUsableLinkedContext, type LinkedWorkItemContext } from './linked-work-item-context'

export function isBeadsWorkItemReference(
  args:
    | { provider?: TaskProvider; beadsIdentifier?: string; linkedContext?: LinkedWorkItemContext }
    | null
    | undefined
): boolean {
  return (
    args?.provider === 'beads' ||
    Boolean(args?.beadsIdentifier?.trim()) ||
    args?.linkedContext?.provider === 'beads'
  )
}

export type BeadsLaunchContextArgs = {
  identifier: string | undefined
  title?: string
  linkedContext?: LinkedWorkItemContext
}

// Why: a bead title is user-authored text heading an agent prompt; escape
// control chars so an embedded newline cannot inject fake instructions.
export function buildBeadsLaunchContextBlock(args: BeadsLaunchContextArgs): string | null {
  const identifier = args.identifier?.trim()
  if (!identifier) {
    return null
  }
  // Why: unlike a Linear/Jira linkedContext (a large snapshot fetched from that
  // provider, deliberately kept out of the prompt — see linked-work-item-context.test.ts's
  // expectNoLinearTicketContent), a beads linkedContext is generated by us
  // (beads-epic-launch-context.ts), already escaped, and never persisted. It's safe
  // and intended to reach the prompt verbatim, so prefer it over the regenerated
  // two-line block when one is present.
  const usableContext = getUsableLinkedContext(args.linkedContext)
  if (usableContext && usableContext.provider === 'beads') {
    return usableContext.renderedText
  }
  const safeIdentifier = escapeLinkedContextControlChars(identifier)
  // Why: WorkspaceLinkedItem.title for beads already carries "<id> <title>"
  // (buildBeadsLinkedItem bakes the id in, matching the Linear/Jira "number===0 ⇒
  // title stands alone" pill convention in workspace-source.ts) — strip a leading
  // identifier here or this line doubles it: "<id> — <id> <title>".
  const rawTitle = args.title?.trim() ?? ''
  // Why no /i flag: every real caller passes the case-exact `${issue.id} ${issue.title}`
  // (buildBeadsLinkedItem), so case-insensitive matching here has no caller to serve.
  const strippedTitle = rawTitle.replace(new RegExp(`^${escapeRegex(identifier)}\\s*[:-]?\\s*`), '')
  const title = escapeLinkedContextControlChars(strippedTitle)
  const summary = title
    ? `Linked Beads issue: ${safeIdentifier} — ${title}`
    : `Linked Beads issue: ${safeIdentifier}`
  return [
    summary,
    `Read it with \`bd show ${safeIdentifier}\` (run \`bd prime\` for workflow context).`
  ].join('\n')
}
